# Generated by Django 3.0.2 on 2020-01-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('pay_type', models.CharField(max_length=100, verbose_name='方法')),
                ('colomun_type', models.CharField(max_length=100, verbose_name='カテゴリ')),
                ('colomun', models.CharField(max_length=100, verbose_name='カテゴリの内訳')),
                ('pay_trans', models.CharField(max_length=100, verbose_name='入金先')),
                ('value', models.IntegerField(verbose_name='合計')),
            ],
        ),
    ]
