# Generated by Django 3.0.2 on 2020-01-28 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregate', '0002_auto_20200128_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aggregate',
            old_name='columun',
            new_name='column',
        ),
        migrations.RenameField(
            model_name='aggregate',
            old_name='columun_type',
            new_name='column_type',
        ),
    ]
