# Generated by Django 3.0.2 on 2020-01-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('sub', models.CharField(max_length=100)),
            ],
        ),
    ]
