# Generated by Django 3.0.2 on 2020-02-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='名前')),
                ('age', models.CharField(blank=True, max_length=100, verbose_name='年齢')),
                ('visit', models.CharField(blank=True, max_length=100, verbose_name='住み')),
                ('work', models.CharField(blank=True, max_length=100, verbose_name='仕事')),
                ('hobby', models.CharField(blank=True, max_length=100, verbose_name='趣味')),
                ('birth', models.DateField(blank=True, verbose_name='誕生日')),
                ('co_date', models.DateField(blank=True, verbose_name='記念日')),
                ('date', models.DateField(blank=True, verbose_name='LINE開始日')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('scenario', models.CharField(blank=True, max_length=100, verbose_name='シナリオ')),
            ],
        ),
    ]
