# Generated by Django 3.0.2 on 2020-02-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='actress',
            name='co_date',
            field=models.DateField(blank=True, null=True, verbose_name='記念日'),
        ),
        migrations.AlterField(
            model_name='actress',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='LINE開始日'),
        ),
    ]
