# Generated by Django 2.2.4 on 2020-02-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actress', '0002_auto_20200219_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='actress',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
