# Generated by Django 2.2.4 on 2020-02-20 04:36

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('actress', '0003_actress_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
