# Generated by Django 2.2.4 on 2020-02-20 05:40

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('actress', '0004_auto_20200220_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='path/to/images'),
        ),
    ]
