# Generated by Django 2.2.4 on 2020-02-20 05:44

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('actress', '0006_auto_20200220_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='image',
            field=stdimage.models.StdImageField(blank=True, default=234, upload_to='media'),
            preserve_default=False,
        ),
    ]
