# Generated by Django 2.2.4 on 2020-02-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actress', '0007_auto_20200220_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='actress',
            name='no',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID'),
        ),
    ]
