# Generated by Django 3.0.2 on 2020-02-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actress', '0008_auto_20200220_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actress/media'),
        ),
    ]
