# Generated by Django 3.0.2 on 2020-02-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actress', '0009_auto_20200220_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
