# Generated by Django 3.0.2 on 2020-02-21 06:34

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('actress', '0010_auto_20200220_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='image',
            field=stdimage.models.StdImageField(blank=True, default=234, upload_to='media'),
            preserve_default=False,
        ),
    ]
