# Generated by Django 3.0.2 on 2020-04-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actress', '0011_auto_20200221_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='actress',
            name='car',
            field=models.BooleanField(blank=True, null=True, verbose_name='車'),
        ),
        migrations.AddField(
            model_name='actress',
            name='career',
            field=models.TextField(blank=True, null=True, verbose_name='経歴'),
        ),
        migrations.AddField(
            model_name='actress',
            name='family',
            field=models.TextField(blank=True, null=True, verbose_name='家族メモ'),
        ),
        migrations.AddField(
            model_name='actress',
            name='judgment',
            field=models.CharField(blank=True, max_length=100, verbose_name='性格判定'),
        ),
        migrations.AddField(
            model_name='actress',
            name='my_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='伝えた誕生日'),
        ),
    ]
