# Generated by Django 3.0.2 on 2020-04-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actress', '0012_auto_20200403_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actress',
            name='judgment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='性格判定'),
        ),
    ]
